import * as React from 'react';
import { Platform, Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { FocusAwareStatusBar, Text } from '@/components/ui';

export { Text };

export const C = {
  cream: '#F6EEE1', ink: '#3A2C1E', muted: '#97806A', border: '#E5D5BE', brick: '#8D3117', brickDark: '#692411', mud: '#A9714A', gold: '#C9A24B', green: '#6E8F5E', greenDark: '#547048', greenLight: '#EAF0E5', red: '#B5563C', redLight: '#FBEAE4', white: '#FFFFFF', paper: '#FAF6EF', blueLight: '#EFF6FF', yellowLight: '#FBF3E1',
};

export function Screen({ children, scroll = true }: { children: React.ReactNode; scroll?: boolean }) {
  const content = <View style={styles.container}>{children}</View>;
  return <SafeAreaView style={styles.safe}><FocusAwareStatusBar />{scroll ? <ScrollView contentContainerStyle={styles.scroll}>{content}</ScrollView> : content}</SafeAreaView>;
}

export function Eyebrow({ children }: { children: React.ReactNode }) { return <Text style={styles.eyebrow}>{children}</Text>; }
export function Title({ children, subtitle }: { children: React.ReactNode; subtitle?: React.ReactNode }) { return <View style={styles.titleBlock}><Text style={styles.title}>{children}</Text>{subtitle && <Text style={styles.subtitle}>{subtitle}</Text>}</View>; }
export function Card({ children, style }: { children: React.ReactNode; style?: object }) { return <View style={[styles.card, style]}>{children}</View>; }
export function SectionHeader({ title, detail, action }: { title: string; detail?: string; action?: React.ReactNode }) { return <View style={styles.sectionHeader}><View><Text style={styles.sectionTitle}>{title}</Text>{detail && <Text style={styles.eyebrow}>{detail}</Text>}</View>{action}</View>; }
export function Button({ label, onPress, variant = 'primary', disabled = false }: { label: string; onPress?: () => void; variant?: 'primary' | 'outline' | 'danger' | 'ghost'; disabled?: boolean }) { return <Pressable disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.button, variant === 'primary' && styles.primary, variant === 'danger' && styles.danger, variant === 'ghost' && styles.ghost, pressed && styles.pressed, disabled && styles.disabled]}><Text style={[styles.buttonText, variant === 'primary' && styles.primaryText, variant === 'danger' && styles.dangerText, variant === 'ghost' && styles.ghostText]}>{label}</Text></Pressable>; }
export function Field({ label, value, onChangeText, placeholder, keyboardType = 'default', multiline = false }: { label: string; value: string; onChangeText: (value: string) => void; placeholder?: string; keyboardType?: 'default' | 'numeric' | 'phone-pad'; multiline?: boolean }) { return <View style={styles.field}><Text style={styles.fieldLabel}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={C.muted} keyboardType={keyboardType} multiline={multiline} style={[styles.input, multiline && styles.multiline]} /></View>; }
export function Chip({ children, tone = 'neutral' }: { children: React.ReactNode; tone?: 'neutral' | 'green' | 'gold' | 'red' }) { return <View style={[styles.chip, tone === 'green' && { backgroundColor: C.greenLight }, tone === 'gold' && { backgroundColor: C.yellowLight }, tone === 'red' && { backgroundColor: C.redLight }]}><Text style={[styles.chipText, tone === 'green' && { color: C.greenDark }, tone === 'gold' && { color: '#8A6A1F' }, tone === 'red' && { color: C.red }]}>{children}</Text></View>; }
export function Stat({ label, value, hint, tone = 'green' }: { label: string; value: string; hint?: string; tone?: 'green' | 'gold' | 'red' | 'brick' }) { const background = tone === 'green' ? C.greenLight : tone === 'gold' ? C.yellowLight : tone === 'red' ? C.redLight : '#F4E9E5'; const color = tone === 'green' ? C.greenDark : tone === 'gold' ? '#9C7A2E' : tone === 'red' ? C.red : C.brick; return <View style={[styles.stat, { backgroundColor: background }]}><Eyebrow>{label}</Eyebrow><Text style={[styles.statValue, { color }]}>{value}</Text>{hint && <Eyebrow>{hint}</Eyebrow>}</View>; }

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.cream }, scroll: { paddingBottom: 32 }, container: { width: '100%', maxWidth: 1180, alignSelf: 'center', paddingHorizontal: 20, paddingTop: 14, gap: 16 }, titleBlock: { gap: 4, marginBottom: 4 }, eyebrow: { color: C.muted, fontSize: 12 }, title: { color: C.ink, fontSize: 28, lineHeight: 34, fontWeight: '800', letterSpacing: -0.5 }, subtitle: { color: C.muted, fontSize: 13, lineHeight: 19 }, card: { backgroundColor: 'rgba(255,255,255,0.9)', borderColor: C.border, borderWidth: 1, borderRadius: 16, padding: 16, gap: 10, ...Platform.select({ web: { boxShadow: '0 6px 18px rgba(122,79,49,0.10)' }, default: { shadowColor: '#7A4F31', shadowOpacity: 0.1, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 2 } }) }, sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', gap: 12, marginTop: 8 }, sectionTitle: { color: C.ink, fontSize: 19, fontWeight: '800' }, button: { alignItems: 'center', justifyContent: 'center', borderRadius: 12, borderColor: C.border, borderWidth: 1, minHeight: 42, paddingHorizontal: 15 }, primary: { backgroundColor: C.brick, borderColor: C.brickDark }, danger: { backgroundColor: C.redLight, borderColor: '#E8C4B4' }, ghost: { backgroundColor: 'transparent', borderColor: 'transparent' }, buttonText: { color: C.ink, fontWeight: '700', fontSize: 13 }, primaryText: { color: C.white }, dangerText: { color: C.red }, ghostText: { color: C.brick }, pressed: { opacity: 0.78, transform: [{ scale: 0.99 }] }, disabled: { opacity: 0.45 }, field: { gap: 5, flex: 1, minWidth: 140 }, fieldLabel: { color: C.muted, fontSize: 11, fontWeight: '600' }, input: { backgroundColor: C.white, borderColor: C.border, borderWidth: 1, borderRadius: 12, minHeight: 44, paddingHorizontal: 12, color: C.ink, fontSize: 13 }, multiline: { minHeight: 78, paddingTop: 12, textAlignVertical: 'top' }, chip: { alignSelf: 'flex-start', borderColor: C.border, borderWidth: 1, backgroundColor: C.paper, borderRadius: 99, paddingHorizontal: 10, paddingVertical: 6 }, chipText: { color: C.muted, fontSize: 11, fontWeight: '700' }, stat: { flex: 1, minWidth: 145, borderRadius: 15, padding: 15, gap: 7 }, statValue: { fontSize: 21, fontWeight: '800' },
});
